/**
 * Paper-backed content and external-resource configuration.
 * Empty link strings are disabled automatically by the UI.
 */
window.PROJECT_DATA = {
  title: "Towards Fine-Grained Object Manipulation: SAM3-Guided Visuomotor Policy with Persistent Memory Learning and Focused Visual Conditioning",
  venue: "ICRA 2027 Submission",
  abstract: [
    "Fine-grained object (FO) manipulation requires robots to distinguish a specified FO from visually similar objects and execute actions reliably despite scene distractors. However, scene-level visual conditioning lacks explicit object selection, while category-level guidance cannot reliably distinguish FOs within the same category. We present a SAM3-guided visuomotor framework that addresses these challenges through persistent object memory and focused visual conditioning. First, we introduce FO Memory-driven SAM3 (FOM-SAM3), which learns reusable FO memory tokens from limited multi-view registration images while keeping SAM3 fully frozen. Through one-vs-rest learning, these tokens encode persistent memories for localizing target FOs and rejecting similar alternatives, which can be stored in a memory bank. Second, we propose Focused Spatial-Appearance Encoding (FSAE), which combines in-FO local appearance features with explicit bounding-box coordinates to condition action policies including Diffusion Policy (DP) and Action Chunking with Transformers (ACT). The effectiveness of the proposed FOM-SAM3 is validated on the FO-30 dataset comprising 30 physical objects across four coarse categories. Across three real-robot FO manipulation tasks, our FOM-SAM3-guided policies demonstrated the robustness against distractors, discriminative ability of similar FOs, and extendibility to new FOs.",
  ],
  abstractHighlights: [
    "fine-grained object (FO)",
    "FO Memory-driven SAM3 (FOM-SAM3)",
    "reusable FO memory tokens",
    "Focused Spatial-Appearance Encoding (FSAE)",
    "FO-30 dataset",
    "three real-robot FO manipulation tasks",
  ],
  links: {
    paper: "",
    arxiv: "",
    code: "",
    video: "#demonstrations-title",
  },
  demoVideos: [
    { src: "assets/videos/1.mp4", title: "Collect Can · Continuous long-horizon rollout" },
    { src: "assets/videos/2.mp4", title: "Push Box · Continuous long-horizon rollout" },
    { src: "assets/videos/3.mp4", title: "Lid Cup · Continuous long-horizon rollout" },
    { src: "assets/videos/4.mp4", title: "Collect Can · Cluttered scene" },
    { src: "assets/videos/5.mp4", title: "Collect Can · Background change" },
    { src: "assets/videos/pick_place_id_ours_dp_01.mp4", poster: "assets/videos/pick_place_id_ours_dp_01.jpg", title: "DemoFO · Ours-DP" },
    { src: "assets/videos/pick_place_ood_similar_ours_dp_01.mp4", poster: "assets/videos/pick_place_ood_similar_ours_dp_01.jpg", title: "SimilarFO distractors · Ours-DP" },
    { src: "assets/videos/pick_place_within_type_new_fos_ours_dp_01.mp4", poster: "assets/videos/pick_place_within_type_new_fos_ours_dp_01.jpg", title: "Switch FO Memory · SimilarFO1 · Ours-DP" },
    { src: "assets/videos/pick_place_within_type_new_fos_ours_dp_02.mp4", poster: "assets/videos/pick_place_within_type_new_fos_ours_dp_02.jpg", title: "Frozen-policy SimilarFO reuse · SimilarFO2 · Ours-DP" },
    { src: "assets/videos/gen5.mp4", title: "Push Box · FO: tea soda bottle" },
    { src: "assets/videos/gen6.mp4", title: "Push Box · FO: green plastic cup" },
    { src: "assets/videos/gen7.mp4", title: "Lid Cup · FO: tape" },
    { src: "assets/videos/gen8.mp4", title: "Lid Cup · FO: penguin toy" },
    { src: "assets/videos/gen9.mp4", title: "Lid Cup · FO: tape" },
    { src: "assets/videos/gen10.mp4", title: "Push Box · FO: Rubik's cube" },
    { src: "assets/videos/gen11.mp4", title: "Push Box · FO: tissue box" },
  ],
  generalizationDemos: [
    { task: "Collect Can", fo: "SimilarFO1", method: "Ours-DP", src: "assets/videos/pick_place_within_type_new_fos_ours_dp_01.mp4", poster: "assets/videos/pick_place_within_type_new_fos_ours_dp_01.jpg" },
    { task: "Collect Can", fo: "SimilarFO1", method: "Ours-ACT", src: "assets/videos/pick_place_within_type_new_fos_ours_act_01.mp4", poster: "assets/videos/pick_place_within_type_new_fos_ours_act_01.jpg" },
    { task: "Collect Can", fo: "SimilarFO2", method: "Ours-DP", src: "assets/videos/pick_place_within_type_new_fos_ours_dp_02.mp4", poster: "assets/videos/pick_place_within_type_new_fos_ours_dp_02.jpg" },
    { task: "Collect Can", fo: "SimilarFO2", method: "Ours-ACT", src: "assets/videos/pick_place_within_type_new_fos_ours_act_02.mp4", poster: "assets/videos/pick_place_within_type_new_fos_ours_act_02.jpg" },
    { task: "Push Box", fo: "SimilarFO1", method: "Ours-DP", src: "assets/videos/push_within_type_new_fos_ours_dp_01.mp4", poster: "assets/videos/push_within_type_new_fos_ours_dp_01.jpg" },
    { task: "Push Box", fo: "SimilarFO1", method: "Ours-ACT", src: "assets/videos/push_within_type_new_fos_ours_act_01.mp4", poster: "assets/videos/push_within_type_new_fos_ours_act_01.jpg" },
    { task: "Push Box", fo: "SimilarFO2", method: "Ours-DP", src: "assets/videos/push_within_type_new_fos_ours_dp_02.mp4", poster: "assets/videos/push_within_type_new_fos_ours_dp_02.jpg" },
    { task: "Push Box", fo: "SimilarFO2", method: "Ours-ACT", src: "assets/videos/push_within_type_new_fos_ours_act_02.mp4", poster: "assets/videos/push_within_type_new_fos_ours_act_02.jpg" },
    { task: "Lid Cup", fo: "SimilarFO1", method: "Ours-DP", src: "assets/videos/assemble_within_type_new_fos_ours_dp_01.mp4", poster: "assets/videos/assemble_within_type_new_fos_ours_dp_01.jpg" },
    { task: "Lid Cup", fo: "SimilarFO1", method: "Ours-ACT", src: "assets/videos/assemble_within_type_new_fos_ours_act_01.mp4", poster: "assets/videos/assemble_within_type_new_fos_ours_act_01.jpg" },
    { task: "Lid Cup", fo: "SimilarFO2", method: "Ours-DP", src: "assets/videos/assemble_within_type_new_fos_ours_dp_02.mp4", poster: "assets/videos/assemble_within_type_new_fos_ours_dp_02.jpg" },
    { task: "Lid Cup", fo: "SimilarFO2", method: "Ours-ACT", src: "assets/videos/assemble_within_type_new_fos_ours_act_02.mp4", poster: "assets/videos/assemble_within_type_new_fos_ours_act_02.jpg" },
  ],
  sceneGeneralizationDemos: [
    { setting: "Background Change", fo: "Red Wontae Strawberry Juice Can", src: "assets/videos/gen1.mp4" },
    { setting: "Background Change", fo: "Red Wontae Strawberry Juice Can", src: "assets/videos/gen2.mp4" },
    { setting: "Cluttered Scene", fo: "Red CocaCola Soda Can", src: "assets/videos/gen3.mp4" },
    { setting: "Cluttered Scene", fo: "Red Wontae Strawberry Juice Can", src: "assets/videos/gen4.mp4" },
  ],
  taskPrompts: {
    "Collect Can": "red CocaCola soda can",
    "Push Box": "white pill box",
    "Lid Cup": "cup lid with panda handle",
  },
  robotResults: [
    { method: "RGB-DP", id: ["8/10", "7/10", "5/10"], distractors: ["6/10", "3/10", "5/10"], similar: ["1/10", "3/10", "0/10"] },
    { method: "S²-Diff.", id: ["10/10", "7/10", "4/10"], distractors: ["8/10", "6/10", "5/10"], similar: ["4/10", "6/10", "5/10"] },
    { method: "Ours-DP", id: ["10/10", "9/10", "8/10"], distractors: ["10/10", "8/10", "10/10"], similar: ["10/10", "10/10", "10/10"], ours: true },
    { method: "RGB-ACT", id: ["10/10", "8/10", "6/10"], distractors: ["4/10", "5/10", "3/10"], similar: ["0/10", "5/10", "1/10"] },
    { method: "Ours-ACT", id: ["10/10", "9/10", "9/10"], distractors: ["8/10", "10/10", "9/10"], similar: ["8/10", "9/10", "7/10"], ours: true },
  ],
};
